version: '3'
services:
  # Service MongoDB
  mongo:
    image: mongo
    container_name: my_mongo
    ports:
      - "8000:27017"

    networks:
      - mynetwork

  # Service FastAPI
  fastapi:
    build:
      context: ./  # Chemin vers le répertoire de votre application FastAPI
    container_name: my_fastapi
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    networks:
      - mynetwork
    

networks:
  mynetwork: